import Head from "next/head";
import Message from "../components/Message";
import { useState, useEffect } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

export default function Home() {
  // Create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Twitter - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full md:max-w-2xl md:mx-auto min-h-[100vh] my-10">
        <h1 className="text-lg text-gray-600 font-medium my-10">
          See what other people are saying
        </h1>

        <div className="flex flex-col gap-5">
          {allPosts.map((post) => (
            <Message key={post.id} {...post}>
              <Link
                href={{ pathname: `/posts/${post.id}`, query: { ...post } }}
              >
                <button className="text-sm text-cyan-500">
                  {post.comments?.length > 0 ? post.comments?.length : 0}
                  {" " + "comments"}
                </button>
              </Link>
            </Message>
          ))}
        </div>
      </div>
    </div>
  );
}
